### ISSUE TITLE
Can generated getSchema method always return same Schema instance?

### ISSUE THREAD

**Issue by zcox** [julianpeeters/avro-scala-macro-annotations#10]
When using `@AvroRecord`, the generated `getSchema` method returns a new instance of `Schema` on every call. This could be inefficient in general, and caused this specific issue for me recently:

https://groups.google.com/d/msg/confluent-platform/gkmtn2FO4Ug/IIsp8tZHT0QJ

Would it be possible to have every instance of the same case class return the same `Schema` instance? I think ending up with something like this would work:

```scala
@AvroRecord
case class MyMessage(var a: String, var b: Int) {
  //generated getSchema method
  def getSchema: Schema = MyMessage.schema
}

//generated companion object
object MyMessage {
  lazy val schema = new Schema.Parser().parse(${generateSchema(name.toString, namespace, indexedFields).toString})
}
```

This seems to be essentially what the Avro Java code generator produces (a `static final Schema` object). I could try taking a run at this, but I've never done anything with Scala macros before so might take awhile. Mainly just wanted to open this issue to get thoughts from others.

**Comment by julianpeeters** [comment]
Yes.

I see 
```scala
public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(" ... 
```

With respect to naming, do you prefer `schema` to `SCHEMA$`?

With respect to timing, maybe tonight. 

I don't mean to steal your fun! The fix for [issue #1](https://github.com/julianpeeters/avro-scala-macro-annotations/issues/1) gets us almost all the way there. The hard parts were:
 1) what does a companion object definition look like when it is extracted/decomposed into its AST (err, into the quasiquote representation of its AST)
2) where to splice in such a definition 

This ought to do the trick, pattern match *in* an annotated class and emit an updated class and companion object:

```scala
q"""$mods class $name[..$tparams](..$first)(...$rest) extends ..$newParents { $self => ..$newBody };
              object ${newTermName(name.toString)} { $newVal }""" 
```

**Comment by zcox** [comment]
@julianpeeters awesome, glad this can be fixed! I'm pretty much indifferent on naming of the companion object schema field, although the [Scala style guide](http://docs.scala-lang.org/style/naming-conventions.html#constants-values-variable-and-methods) says "Constant names should be in upper camel case" so maybe it should be named `Schema`?

**Comment by julianpeeters** [comment]
Sorry for any trouble this has caused you. 

Does version 0.7 solve your issues? (Now up at Sontatype, syncing with Maven Central soon) 

Was kinda locked into using "SCHEMA$" already, so without a strong objection, there it is, '$' in the name and all :8ball:

**Comment by zcox** [comment]
Just tested this out in 0.7 with the kafka schema registry - works great! Thanks a bunch for fixing this so quickly! :100:
