### ISSUE TITLE
Binary Avro representation fails

### ISSUE THREAD

**Issue by sutram** [julianpeeters/avro-scala-macro-annotations#12]
Hi,
I am trying to use the @AvroRecord annotation to create a binary Avro representation of my Scala case classes. It is failing with a null pointer exception and I can't figure out why.

Here is the code:
```scala
import com.julianpeeters.avro.annotations._

import org.apache.avro.specific.{SpecificDatumWriter, SpecificData}
import org.apache.avro.io.EncoderFactory

import java.io.ByteArrayOutputStream

@AvroRecord
case class Platform (
  var deviceId: Option[String],
  var deviceType: Option[String]
)

@AvroRecord
case class Quality (
  var bitrate: Option[Int],
  var previousBitRate: Option[Int]
)

@AvroRecord
case class Playback (
  var quality: Option[Quality]
)

@AvroRecord
case class AtomicSlice (
  var timestamp_received: Long,
  var platform: Option[Platform],
  var playback: Option[Playback]
)

object ASMain {

  def main(args: Array[String]) = {

    val platform = Platform(deviceId=scala.None, deviceType=Some("abc"))

    val as = AtomicSlice(
      timestamp_received=1234567890000L,
      platform=Some(platform),
      playback=scala.None)

    println(AtomicSlice.SCHEMA$)

    val sw = new SpecificDatumWriter[AtomicSlice]

    val out = new java.io.ByteArrayOutputStream()
    val encoder = EncoderFactory.get().binaryEncoder(out, null)
    sw.write(as, encoder)
    encoder.flush
    val ba = out.toByteArray
    out.close


  }
}
```

Here is the exception:
```
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:87)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
        at com.twc.needle.domain.ASMain$.main(AtomicSlice.scala:51)
        at com.twc.needle.domain.ASMain.main(AtomicSlice.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by julianpeeters** [comment]
Hi Sutram, 

Thanks for trying out this library. 

Use the schema as an argument to the datumwriter:
```scala
    val sw = new SpecificDatumWriter[AtomicSlice](AtomicSlice.SCHEMA$)
```

The above is how I see SpecificDatumWriters used in this [Avro test](https://github.com/apache/avro/blob/6a80468a68de9bd035d5cc21d2ee664e1956c884/lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificData.java#L164) and in an [hbase example](http://www.programcreek.com/java-api-examples/index.php?api=org.apache.avro.specific.SpecificDatumWriter) (according to a quick web search). Without specifying a schema, I get the same error in Java too(see below). 



I consider this an Avro gotcha because SpecificDatumWriters need to be constructed differently for writing files than for writing straight binary, but we get no help from the compiler. All avro writing requires a schema at some point. DataFileWriters require a schema be specified upon file creation, so it doesn't matter if their datumwriters were constructed with schemas or not. Meanwhile, Encoders don't allow a schema to be specified: if its datumwriter was constructed without one, its schema never gets set and hence the null pointer exception when a write is actually perfomed.

At least this is how things appear to me; although I don't exactly see where things fall through to generic... perhaps the schema didn't match a class name because the schema was null, but why didn't that show up in the stack trace? 

Anyways, hope this helps,
-Julian



The error in java:

    mvn exec:java -Dexec.mainClass="com.example.Main"  
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building avro-encoder-example 1.0.0
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ avro-encoder-example ---
    [WARNING] 
    java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:87)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at com.example.Main.main(Main.java:38)

**Comment by sutram** [comment]
Thanks, that fixed it!

I really appreciate this project.

I have a couple more issues I wanted to run by you so I'll create those as separate issues.

**Comment by julianpeeters** [comment]
great!
