### ISSUE TITLE
Serializing with generic writer and deserializing with specific reader

### ISSUE THREAD

**Issue by eduardojld** [julianpeeters/avro-scala-macro-annotations#33]
Is that possible? Im rewriting some stuff using your library and came across this issue that when using generics for serializing and then your lib for deserializing using specific reader its not grabbing an int union, but just putting a null value

So, in this test you can see whats the deal, I have a base schema which I am expanding with your lib, I took it and added a gender field, so I can serialize using generics and then deserialize using the base one on the case class, below the code

```
val schema2 = new Schema.Parser().parse("""{
      "namespace": "example.avro",
      "type": "record",
      "name": "Person",
      "fields": [
         {"name": "name", "type": "string"},
         {"name": "age", "type": ["int", "null"]},
         {"name": "gender", "type": ["string", "null"]}
      ]
    }""")

    val work = new GenericRecordBuilder(schema2)
      .set("name", "Jeff")
      .set("age", 23)
      .set("gender", "M")
      .build

    val writer = new GenericDatumWriter[GenericRecord](schema2)
    val baos = new ByteArrayOutputStream
    val encoder = EncoderFactory.get().binaryEncoder(baos, null);
    writer.write(work, encoder)
    encoder.flush
    println(work)

    val datumReader = new SpecificDatumReader[Person](Person.SCHEMA$);
    val binDecoder = DecoderFactory.get().binaryDecoder(baos.toByteArray, null);
    val gwork2 = datumReader.read(null, binDecoder);

    println(gwork2)
    work.get("name").toString should be(gwork2.get("name").toString)
    work.get("age") should be(gwork2.get("age"))
```

the outputs of the prints are this 

```
{"name": "Jeff", "age": 23, "gender": "M"}
{"name": "Jeff", "age": null}
```
I checked namespaces and everything seems ok, what else could I be missing here?

**Comment by julianpeeters** [comment]
Sorry you're running into trouble, Eduardo. Does swapping the order of the null and the type within the union definitions of schema2 fix the problem? It seems to on my end. But then again, my specs2 version of your test failed before it ever got printed an incorrectly.

If that works, then the failure was because the @AvroRecord annotation doesn't know about the union's order in writers' schemas, it only sees a Scala Option, and when it finds one, it defaults to the suggestions about unions found in the [Avro docs](https://avro.apache.org/docs/1.8.1/spec.html#Unions), which is `null` first.

If switching the order like this is intolerable for your needs, I might suggest checking out [avrohugger](https://github.com/julianpeeters/avrohugger) which will generate persistent code that you can modify by hand to suit your needs.

**Comment by eduardojld** [comment]
I tried a bunch of things, and I was writing all the test I did, including same scenario but using json serializers that did work, when I wasn't sure I did the swapping of the union types right, so I gave it a second try, and... worked like a charm! ¯\_(ツ)_/¯

note: the json test worked with and without the swapping thing!

Thanks for your help!!
